after-login-command = []
after-startup-command = [
    'exec-and-forget borders active_color=0xFFFF79C6 inactive_color=0x88888888 width=5.0',
    'exec-and-forget sketchybar'
]

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 60
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'
automatically-unhide-macos-hidden-apps = true

exec-on-workspace-change = [ '/bin/bash', '-c',
    '$HOME/.config/aerospace/on_workspace_change.sh $AEROSPACE_FOCUSED_WORKSPACE'
]

#  lsappinfo list | fzf

[[on-window-detected]]
if.app-name-regex-substring = '1password'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'picture-in-picture'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'karabiner'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'fantastical'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'drafts'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'music'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'dark noise'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'ColorSlurp'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'zoom'
run = 'layout floating'

# [[on-window-detected]]
# if.app-name-regex-substring = 'obsidian'
# run = 'layout floating'

# [[on-window-detected]]
# if.app-name-regex-substring = 'github'
# run = 'layout floating'

# [[on-window-detected]]
# if.app-name-regex-substring = 'docker desktop'
# run = 'layout floating'

# [[on-window-detected]]
# if.app-name-regex-substring = 'mail'
# run = 'layout floating'

# [[on-window-detected]]
# if.app-name-regex-substring = 'things'
# run = 'layout floating'

# [[on-window-detected]]
# if.app-name-regex-substring = 'todoist'
# run = 'layout floating'


[key-mapping]
    preset = 'qwerty'

[gaps]
    inner.horizontal = 17
    inner.vertical =   17
    outer.left =       13
    outer.bottom =     13
    outer.top =        13
    outer.right =      13

[mode.main.binding]
    # App shortcuts
    alt-b = "exec-and-forget open -a /Applications/'Zen Browser.app'"
    alt-c = 'exec-and-forget open -a /Applications/Cursor.app'
    alt-q = 'exec-and-forget open -a /Applications/Ghostty.app'
    alt-shift-r = ['exec-and-forget /opt/homebrew/bin/sketchybar --reload']

    alt-period = 'layout tiles horizontal vertical'
    alt-o = 'layout accordion horizontal vertical'
    alt-enter = 'fullscreen'
    alt-y = ['focus right', 'join-with down', 'layout tiles horizontal']
    
    alt-h = 'focus left'
    alt-j = 'focus down'
    alt-k = 'focus up'
    alt-l = 'focus right'

    alt-shift-h = 'move left'
    alt-shift-j = 'move down'
    alt-shift-k = 'move up'
    alt-shift-l = 'move right'

    alt-minus = 'resize smart -50'
    alt-equal = 'resize smart +50'

    alt-1 = 'workspace 1'
    alt-2 = 'workspace 2'
    alt-3 = 'workspace 3'
    alt-4 = 'workspace 4'
    alt-5 = 'workspace 5'
    alt-6 = 'workspace 6'
    alt-7 = 'workspace 7'
    alt-8 = 'workspace 8'
    alt-9 = 'workspace 9'

    alt-shift-1 = 'move-node-to-workspace 1'
    alt-shift-2 = 'move-node-to-workspace 2'
    alt-shift-3 = 'move-node-to-workspace 3'
    alt-shift-4 = 'move-node-to-workspace 4'
    alt-shift-5 = 'move-node-to-workspace 5'
    alt-shift-6 = 'move-node-to-workspace 6'
    alt-shift-7 = 'move-node-to-workspace 7'
    alt-shift-8 = 'move-node-to-workspace 8'
    alt-shift-9 = 'move-node-to-workspace 9'

    alt-tab = 'workspace-back-and-forth'
    alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

    # See: https://nikitabobko.github.io/AeroSpace/commands#mode
    alt-shift-semicolon = 'mode service'

[mode.service.binding]
    esc = ['reload-config', 'mode main']
    r = ['flatten-workspace-tree', 'mode main'] # reset layout
    f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
    backspace = ['close-all-windows-but-current', 'mode main']

    # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
    # s = ['layout sticky tiling', 'mode main']

    alt-shift-h = ['join-with left', 'mode main']
    alt-shift-j = ['join-with down', 'mode main']
    alt-shift-k = ['join-with up', 'mode main']
    alt-shift-l = ['join-with right', 'mode main']
