'$schema' = 'https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json'

[general]
allow_concurrent_presets = false

[defaults]
kanata_executable = '~/.config/kanata/kanata_macos_cmd_allowed_arm64' # if empty or omitted, system $PATH will be searched.
kanata_config = '~/.config/kanata/kanata.kbd' # if empty or not omitted, kanata default config locations will be used.

[defaults.hooks]
# Hooks allow running custom commands on specific events (e.g. starting preset).
# Documentation: https://github.com/rszyma/kanata-tray/blob/main/doc/hooks.md

[defaults.layer_icons]
mouse = 'mouse.png'
qwerty = 'qwerty.ico'
'*' = 'other_layers.ico'